### ISSUE TITLE
Music restarting when loading a save or restarting in a map with UMAPINFO-designated music

### ISSUE THREAD

**Issue by Alper002** [coelckers/prboom-plus#102]
Method of reproducing this issue:
Step 1:Get a wad file with a UMAPINFO lump, I.E. [DBP25](https://www.doomworld.com/forum/topic/115453-dbp25-dead-but-dreaming/).
Step 2:Enter a map that was defined via UMAPINFO(in DBP25's case, maps 1-11 and map 33)
Step 3:Save
Step 4:Load save

Alternate step 3/4:warp to the map using the idclev cheat

It can get pretty annoying hearing the start of a music track over and over when you're playing a map, rather than hearing the whole of it as you retry and/or load saves.

**Comment by zstephens** [comment]
The same thing happens with musinfo music (a longstanding bug that I'd been meaning to open an issue here about), and it was fixed in crispy doom. perhaps porting that over here would solve this as well?

Here's the crispy commit: https://github.com/fabiangreffrath/crispy-doom/commit/b1825efe185c761f6bf82c2c88a64c50dcec8ebf

Here's some old discussion from when I had attempted to fix it myself: https://github.com/zstephens/prb-plus2515-test/commit/8eb14370bb624a1789d27ee8efecb05b3af1149e
