### ISSUE TITLE
Terrible problem with ultimate doom episodes.

### ISSUE THREAD

**Issue by JuanchoES** [coelckers/prboom-plus#117]
When I finish the first level of episode 4 with the ultimate doom complevel it sends me back to level 2 of the first chapter of doom, when I finish the first level of episode 2 the next level is correct one but the map screen is mixed with the map of the episode 1.

This does not happen with the latest official version of prboom+.

Im runnig the v2.5.1.7um version.

**Comment by fabiangreffrath** [comment]
This is supposed to be fixed for one year now:
https://github.com/coelckers/prboom-plus/commit/dfe091e35a96e014d3f77c23b198f4a5004c6004#diff-a114c8240db53b91483138ef2ae2c0a4

Please use one of the community provided builds instead of the official release, e.g.:
https://www.doomworld.com/forum/topic/106866-prboomumapinfo-v-2517/?page=13&tab=comments#comment-2151685

@coelckers I guess it's really high time for a new "official" release now!
