### ISSUE TITLE
[Bug] Game exits after text screen

### ISSUE THREAD

**Issue by Porcozo** [coelckers/prboom-plus#118]
After exiting MAP06 in interception 2, the game exits with this message:
![Errormessage](https://user-images.githubusercontent.com/47692609/92310487-5d1b9900-ef85-11ea-9e0e-1692d4cd366f.png)

Here's the corresponding UMAPINFO lines:
map MAP06
{
	levelname = "What Could Go Wrong?"
	levelpic = "CWILV05"
	next = "MAP07"
	nextsecret = "MAP31"
	skytexture = "SKY1"
	music = "D_THE_DA"
	exitpic = "INTERPIC"
	enterpic = "INTERPIC"
	partime = 0
	endgame = false
	intertext = "You refuse to let the secrets of the under",
		"world corrupt your mind.",
		"",
		"At least that's what you've been telling",
		"yourself since you got here. The demons",
		"have a beautiful way of whispering into",
		"your psyche's deepest reaches...",
		"",
		"In short, it's a miracle you haven't",
		"been transformed into one of them. And",
		"yet, it remains harder than ever to",
		"recall how long it's been since you left",
		"Earth..."
	interbackdrop = "GSTONEF"
	intermusic = "D_READ_M"
	intertextsecret = clear
}

I'm using seed's build from july 1st.

**Comment by JadingTsunami** [comment]
Looks like a real bug to me. The line below I believe has the boolean check inverted.

```
prboom2/src/umapinfo.cpp:362
	else if (!stricmp(pname, "endgame"))
	{
		scanner.MustGetToken(TK_BoolConst);
/* this if check should be for !scanner.boolean */
		if (scanner.boolean) strcpy(mape->endpic, "!");
		else strcpy(mape->endpic, "-");
	}
```

**Comment by JadingTsunami** [comment]
This appears to be a bug to me. Putting "endgame = false" but no endpic will cause this crash, whereas I believe the correct behavior would be to proceed to the next level.

I believe this is caused by the fact that the finale handler will check for the presence of any nonzero character in the first position of the endpic string as evidence that the endgame should be triggered, but "endgame = false" will copy a "-" into endpic, thereby triggering those conditions to evaluate true.

The fix is either to nullify the first character of endpic when the "endgame = false" token is parsed from the UMAPINFO lump, or modify the endpic checks to look for "!= '-'" instead of a null check on the zeroth character of endpic.

The former seems right to me, but I will see what others think in this comment section. I'd be happy to submit a PR to fix this as it appears to be a straightforward fix in either case.

**Comment by fabiangreffrath** [comment]
@JadingTsunami Please file a PR. It is a lot easier to discuss code changes with the proposed code at sight.

**Comment by fabiangreffrath** [comment]
https://github.com/coelckers/prboom-plus/commit/2607327856d0eddfcef76198a6e81aaadf387c6d
