### ISSUE TITLE
Cannot draw weapons, stuck on angry face

### ISSUE THREAD

**Issue by runlow** [coelckers/prboom-plus#131]
I don't have the exact steps to reproduce this bug but will provide them once I figure them out.

**Expected:**
Can always switch weapons.

**Actual:**
Sometimes doomguy's face "gets stuck" on the angry face (as in defaults to it) and can no longer draw any weapon.
By that I mean that I'm pressing 1-7 and nothing happens. No weapon is displayed either. Can't shoot.

**Extra:**
Saving and loading the game on the same session doesn't seem to set it back to normal behaviour.
Toggling IDDQD or IDCLIP when the bug kicks in doesn't seem to do anything useful.
Dying seems to reset it back to normal though.

**Edit:**
Save file (change extension from 'docx' to 'dsg')
[prboom-plus-savegame0.docx](https://github.com/coelckers/prboom-plus/files/5516800/prboom-plus-savegame0.docx)
Restarting the program and loading the save doesn't restore normal behaviour.

Died a good few times due to this.

The problem apparently started since I compiled  534f9552 and haven't experienced it back when I used 47ebaf83 or so (or maybe just didn't take much note of it back then).

**Comment by JadingTsunami** [comment]
I've observed this too. It seems to happen when all or some of the following are true:

- A large damage (possibly enough to trigger "ouch" face?) is taken by the player all at once
- In the middle of a weapon switch
- Maybe just after or while firing a lot (triggering "angry" face?)

I haven't looked into the code much. So this is just observational and anecdotal.

**Comment by fabiangreffrath** [comment]
Wow, this sounds like a pretty severe bug! @runlow The two commits that you mention in your report seem unrelated, but this one appears suspicious, as it is within that range and affects weapon switching:
https://github.com/coelckers/prboom-plus/commit/be592357a8251b2452d6147f16392d2577877257

However, we will only know for sure if we have a chance to inspect your savegame.

**Comment by fabiangreffrath** [comment]
The "angry face" being drawn in the status bar is an indication that `players[consoleplayer].attackdown` is `true` which triggers the code path in question in the suspicious commit:
https://github.com/coelckers/prboom-plus/blob/2607327856d0eddfcef76198a6e81aaadf387c6d/prboom2/src/g_game.c#L549

The plot thickens...

**Comment by bradharding** [comment]
Missing parentheses in that suspicious commit?

**Comment by fabiangreffrath** [comment]
It could even be that simple, sure. Maybe @38-vita-38 himself could shed some light on this?

**Comment by fabiangreffrath** [comment]
The second line of  the condition in question was probably meant to read
```
!P_CheckAmmo(&players[consoleplayer]) && !done_autoswitch && boom_autoswitch) ||
```

**Comment by runlow** [comment]
Restarting the program and loading the save doesn't restore normal behaviour. 
Now I have the save file. Attaching it with this post.

The bug kicks in also without PWADs and it just happens that I noticed it while running it with a PWAD.

The save file requires Alien Vendetta.
https://www.doomworld.com/idgames/levels/doom2/megawads/av
The command was:
`glboom-plus -iwad DOOM2.WAD -file /tmp/zip/AVMOVFIX.WAD /tmp/zip/AV.WAD -deh /tmp/zip/AV.DEH`

**Save file:**
[prboom-plus-savegame0.docx](https://github.com/coelckers/prboom-plus/files/5516800/prboom-plus-savegame0.docx)

**Please rename the file as it wouldn't allow me to upload it with the "dsg" file extension**
`mv prboom-plus-savegame0.docx prboom-plus-savegame0.dsg`

At first the save will seem OK but if you try to shoot or switch weapons it won't let you.
Hope this helps.

**Comment by runlow** [comment]
I've reverted be59235 on a local branch and compiled.

The save file still works the same way as before (after reverting it and compiling) but I will see if the revert prevents the bug from activating in first place.

I still don't have the exact steps to reproduce the bug yet (except the save file). It just happens to kick in every so often.

As for be59235 I'm not sure I understand what it aims to correct and what prompted it. Maybe there's more info in the pull request?

**Comment by JadingTsunami** [comment]
This might be trickier than it seems. It looks like the player's sprite state information is getting zeroed out somehow.

It can be manually recovered in the debugger, but that doesn't give much clue as to what broke.

**Comment by fabiangreffrath** [comment]
It seems the commit was not at fault, it was a red herring, sorry!

@runlow What exactly happened that led to the weapon switch? Did you run out of ammo, or did you explicitly choose a different weapon (1-9) or did you choose "best available weapon" (0)?

**Comment by fabiangreffrath** [comment]
You may have been hit by this:
https://github.com/coelckers/prboom-plus/commit/3cb143030eb0e02b15b611014c42f5f1d6f73617#diff-1b95bb665ebaed535028d574f33725266e44fde3ccb2af6b80c11ad5fa1c7a72

**Comment by runlow** [comment]
@fabiangreffrath I haven't found a pattern yet to what makes the bug activate in first place but still on the lookout. There's many things happening during combat and the bug kicked in seemingly out of the blue. Maybe I should have been recording a demo for every run - which would have shown the exact steps taken when the bug happened to manifest. I don't remember pressing 0, usually I only press 1-7 for weapons on the keyboard.

Perhaps some of what must have happened can be deduced from the save? I took the save immediately after the bug kicked in. Not sure if it was a "pistol start" or not so some of the necessary conditions for the bug may have been created on the level before it. I'll see if I can find out, also checking what you linked.

**Comment by JadingTsunami** [comment]
@runlow It does seem hard to hit. Similarly I've noticed that it happens when a lot of things happen all at once, *and* a weapon-switch occurs. Whether it's just auto-switch or can be triggered with keys, I don't know. 

Note that since we don't know much about this bug, demo recording may prevent the bug from happening (being in a "demo recording" mode changes *a lot* of gameplay aspects).

Lastly, given we know the signature thanks to the save game, it is possible to detect it at runtime if we get too stuck trying to reproduce the issue reliably. Any time the player (a) is alive, (b) has a zero psprite state and (c) the psprite state has a zero tic length, I think we can safely assume we've hit the invalid condition. This might be useful for debugging or back-tracing.

**Comment by runlow** [comment]
@JadingTsunami Thanks for the extra info/ideas on the signature. Good points about the demo and weapon switch.

If @fabiangreffrath is correct and this has to do with 3cb1430 (and if I understand it correctly) then [a warning should be printed to STDOUT](https://github.com/coelckers/prboom-plus/blob/master/prboom2/src/p_pspr.c#L147) when the bug kicks in. It may have been doing that all along. Haven't been checking it as I wasn't starting the program from a terminal but I could redirect the output to a file and see if shows that message the next time the bug kicks in.

**Comment by fabiangreffrath** [comment]
I guess what we have here is a well known bug, at least among Boom developers - else there wouldn't be an overflow emulation for it. It seems to be a Boom'ism, i.e. something introduced when Boom changed the way weapons are switched. For example, I found the following comment in `A_CheckReload()`:

```
    /* cph 2002/08/08 - In old Doom, P_CheckAmmo would start the weapon lowering
     * immediately. This was lost in Boom when the weapon switching logic was
     * rewritten. But we must tell Doom that we don't need to complete the
     * reload frames for the weapon here. G_BuildTiccmd will set ->pendingweapon
     * for us later on. */
```

Yeah, sure, but somehow this doesn't seem to work reliably. On the other hand, I have never succeeded to reproduce this bug, not even with the `tests/weaponinfo.wad`, but the way this map is set up suggests that it has to do with the player getting hurt (maybe even to health `0`, so the code path in `A_WeaponReady()` is triggered?) but not killed.

Anyway, as you have already found, there is a warning printed to `stderr` when this bug is detected in `P_BringUpWeapon()`. And there is even a bug fix prepared but commented out in `A_Lower()`:

```
   // haleyjd 03/28/10: do not assume pendingweapon is valid
   // e6y: probably for future complevels
   // if(player->pendingweapon < NUMWEAPONS)
  player->readyweapon = player->pendingweapon;
```

**Comment by JadingTsunami** [comment]
I wonder, is it possible that, all in the same tic, the following happen?

1. The player is hurt to the point of health reaching zero
2. The weapon is being lowered to the bottom of the screen and is about to transition to A_Raise of the new weapon
3. The player receives a health item which will raise their health over the "death" point

This could cause a mismatch where the weapon is in the "player is dead" state but the player is still alive, which is what we seem to see here.

I'm not sure it is possible based on the relative ordering of operations within a tic, but I thought I'd ask in case anyone reading knows offhand. I can also dig through the code later if I get some time.

Although this specific sequence seems unlikely to me, I feel it must be something like what is above -- a collision of multiple events in a single tic that, due to order of operations, causes the pending weapon to get "out of sync" and end up in the "player is dead" state.

**Comment by runlow** [comment]
As suspected - it **does** output the message to the console when the bug kicks in. Experienced the bug yet again and checked the console output this time:
```
W_CacheLumpNum: High lock on DSBGDTH2 (15)
W_CacheLumpNum: High lock on DSPOSIT2 (15)
W_CacheLumpNum: High lock on DSPOSIT2 (15)
P_BringUpWeapon: weaponinfo overrun has occurred.
P_BringUpWeapon: weaponinfo overrun has occurred.
W_CacheLumpNum: High lock on DSFIRXPL (95)
W_CacheLumpNum: High lock on DSFIRXPL (95)
W_CacheLumpNum: High lock on DSPSTOP (31)
W_CacheLumpNum: High lock on DSPSTOP (31)
G_DoSaveGame: [8] MAP02 (/tmp/zip/jenesis.wad), Skill 3, Level Time 00:07:44, Total Time 00:07:44
```
It does seem to be related to the "weaponinfo overrun".

**Comment by JadingTsunami** [comment]
> As suspected - it **does** output the message to the console when the reported here bug kicks in. Experienced the it yet again and checked the console output this time:

Do you happen to recall anything about what was happening at the moment when the error happened?

Were you taking damage from enemies or the environment?
Did you initiate the weapon switch with keys, the toggle button, or was it automatic (ran out of ammo, picked up a better weapon or ammo, etc.)?

Anything you recall might be helpful in narrowing down the issue.

**Comment by JadingTsunami** [comment]
Aha! The sequence to get this to happen is tricky. You must have the attack button held down, run out of ammo, switch from the firing weapon to the super shotgun with at least 1 reload's worth of stocked ammo, move through the firing animations, and *then* run out of ammo *again*, all while continuing to hold the "fire" key.

In that case, CheckReload has placed the super shotgun into the lowering state, expecting that G_BuildTiccmd's failed CheckAmmo path will trigger a new weapon to be selected. This used to be true, but it doesn't work now because of the new global variable auto-switch logic that was added in the commit @fabiangreffrath mentioned. So it is indeed that new code causing this bug.

I think refactoring that auto-switch code would be recommended, because linking A_WeaponReady with a global variable indicating weapon auto-switching has occurred seems buggy due to the early exit paths. There may be other ways to exercise this bug I haven't thought of.

**Comment by fabiangreffrath** [comment]
Excellent analysis @JadingTsunami , thank you! I see, so if we enter into `A_WeaponReady()` with the "fire" key held down we will exit early through the `P_FireWeapon()` route and never have the chance to reset the `done_autoswitch` variable at the end of this function. I guess the fix is to consider the weapon switch sequence complete once we enter the `A_WeaponReady()` instead of requiring to run right through it.

**Comment by fabiangreffrath** [comment]
I have created a minimal savegame to reproduce this bug. Just load it and hold the "fire" key.

[prboom-plus-savegame0.zip](https://github.com/coelckers/prboom-plus/files/5581664/prboom-plus-savegame0.zip)

**Comment by fabiangreffrath** [comment]
Please everybody confirm that this patch fixes the bug:
```
--- a/prboom2/src/p_pspr.c
+++ b/prboom2/src/p_pspr.c
@@ -329,6 +329,8 @@ void A_WeaponReady(player_t *player, pspdef_t *psp)
 {
   CHECK_WEAPON_CODEPOINTER("A_WeaponReady", player);

+  done_autoswitch = false;
+
   // get out of attack state
   if (player->mo->state == &states[S_PLAY_ATK1]
       || player->mo->state == &states[S_PLAY_ATK2] )
@@ -371,8 +373,6 @@ void A_WeaponReady(player_t *player, pspdef_t *psp)
     angle &= FINEANGLES/2-1;
     psp->sy = WEAPONTOP + FixedMul(player->bob, finesine[angle]);
   }
-
-  done_autoswitch = false;
 }

 //

```

**Comment by JadingTsunami** [comment]
Yes, this patch works for me (tested on my local machine and confirmed the bug before, same actions, no bug after).

If we are comfortable with the assumption that A_WeaponReady must always be called after a weapon switch happens, then I think we are OK here. I think this is true, but I am not familiar with every code path in the weapon switching logic.

it now makes sense why this bug was called out "when many things were happening", because responding to continuous attacks is the time when the fire button would be held down for a long period of time, enough to cover multiple "out of ammo" situations. This was an interesting one!

**Comment by fabiangreffrath** [comment]
Excellent, thank you for checking!

One thing that's still a bit unclear about the positioning of the variable reset: There is another early exit out of `A_WeaponReady()` that is triggered if either a weapon change is pending or if the player is dead. It seems to be unrelated to the issue reported here and I am unsure if the variable reset has been placed past this exit on purpose. But given that it has been placed past the second exit by mistake - as shown here - I assume not and we should just consider the weapon switch cycle finished once `A_WeaponReady()` is called. Maybe @38-vita-38 could leave a comment in this here just to be sure?

**Comment by runlow** [comment]
Big thanks for looking at this and fixing the bug. Not experiencing it any more. Great work.
