### ISSUE TITLE
videomode reverts back to 8bit

### ISSUE THREAD

**Issue by simc2** [coelckers/prboom-plus#169]
This happens with the prboom-plus "devbuild f29df94 (Jan 12 2021)" from DW. 

When **glboom-plus** is run for the first time (without cfg) it'll default to videomode "8bit":

> videomode "8bit"

The usual outlook of GlBoom is got by selecting OpenGL from the menu: Options > General > Video Mode:

> videomode "OpenGL"

However, if **prboom-plus** is now run the videomode automaticly reverts back to "8bit". And when **glboom-plus** is run again it'll start with videomode "8bit" again.

Could the videomode setting be saved separately for both PrBoom and GlBoom so that they could be changed independently? And the latter one set to "OpenGL" by default for the first time runners without cfg?

Thanks.

**Comment by fabiangreffrath** [comment]
This won't be necessary anymore. In commit https://github.com/coelckers/prboom-plus/commit/c5de4fa9f28458f3e99592fd86e436a14bbb627d the build system was changed to build only one binary. This will always be called `prboom-plus` and it will be OpenGL accelerated if that's available. However, even if this's not possible, since https://github.com/coelckers/prboom-plus/commit/0f9bb9f3454da32e1c6d65a59de01cff7f0060f9 the executable will always preserve all config keys, even the OpenGL-related. Thus, it will be possible to carry the config file between OpenGL and non-OpenGL builds.
