### ISSUE TITLE
[REQUEST] Allow translucency on all complevels

### ISSUE THREAD

**Issue by maxmanium** [coelckers/prboom-plus#246]
Shouldn't affect demos, so I'm not sure why this is complevel'd anyway.

Sorry @fabiangreffrath, just saw your request to post this.

**Comment by fabiangreffrath** [comment]
Thank you for taking the discussion here! The point is, translucency is treated as a fix in PrBoom - but there has never been a bug. Translucency is already optional, so users might switch it on or off as they like. I see no reason to force it off for them on lower complevels.

**Comment by fabiangreffrath** [comment]
```patch
--- a/prboom2/src/g_game.c
+++ b/prboom2/src/g_game.c
@@ -2638,7 +2638,7 @@ void G_Compatibility(void)
     // comp_maxhealth - Max Health in DEH applies only to potions
     { boom_compatibility_compatibility, prboom_6_compatibility },
     // comp_translucency - No predefined translucency for some things
-    { boom_compatibility_compatibility, prboom_6_compatibility },
+    { 0, prboom_6_compatibility },
   };
   unsigned int i;
 
```

**Comment by fabiangreffrath** [comment]
This patch allows for translucency on all complevels and at the same time allows for disabling predefined translucency on all complevels. Additionally, the change of the compatibility option instantly applies to the current game:

```patch
diff --git a/prboom2/src/d_deh.c b/prboom2/src/d_deh.c
index b4c592e8..5c095a47 100644
--- a/prboom2/src/d_deh.c
+++ b/prboom2/src/d_deh.c
@@ -1490,7 +1490,7 @@ void deh_changeCompTranslucency(void)
       }
       else
 #endif
-      if (comp[comp_translucency]) 
+      if (default_comp[comp_translucency])
         mobjinfo[predefined_translucency[i]].flags &= ~MF_TRANSLUCENT;
       else 
         mobjinfo[predefined_translucency[i]].flags |= MF_TRANSLUCENT;
diff --git a/prboom2/src/m_menu.c b/prboom2/src/m_menu.c
index f12059e3..fb546e33 100644
--- a/prboom2/src/m_menu.c
+++ b/prboom2/src/m_menu.c
@@ -3686,7 +3686,7 @@ setup_menu_t comp_settings3[] =  // Compatibility Settings screen #3
   {"Max Health in DEH applies only to potions", S_YESNO, m_null, C_X,
    C_Y + compat_maxhealth * COMP_SPC, {"comp_maxhealth"}},
   {"No predefined translucency for some things", S_YESNO, m_null, C_X,
-   C_Y + compat_translucency * COMP_SPC, {"comp_translucency"}},
+   C_Y + compat_translucency * COMP_SPC, {"comp_translucency"},0,0,deh_changeCompTranslucency},
    // [FG]
   {"allow MBF sky transfers in all complevels", S_YESNO, m_null, C_X,
    C_Y + compat_skytransfers * COMP_SPC, {"comp_skytransfers"}},
```

**Comment by kraflab** [comment]
This is another change that would not be allowed for speedrunning. It's getting to the point where we may just tell people to not use pr+ at all for speedrunning, which isn't really a line I want to cross but it does feel inevitable. That's not a criticism of this change though, most users aren't speedrunners, it's mostly just an observation.

**Comment by fabiangreffrath** [comment]
He, what, why? Who decides what is allowed for speedrunning and what is not? And since you need to trust people anyway not to make trivial source changes to their own port copy, wouldn't it make more sense to demand a clearly defined set of *rules* being followed rather than a specific source port being used? Something like "if you are using Pr+, please disable colored blood and translucency". 

Also, Crispy does also allow for rendering translucent sprites on Vanilla complevels. Are you going to recommend against using it as well?

**Comment by kraflab** [comment]
Speedrunning rules are basically set by discussions and general consensus. We don't allow graphical modifications (understandably this is a bit broken already because, e.g., opengl has various differences from software, but it's a matter of what ships have already sailed). Even mundane things like palette tweaks are banned. The problem is that many new players see pr+ as the go to port for speedrunning and assume that the options in there are allowed if they work with recording. We wouldn't flat out ban a port like that though, but we may for instance start telling players that submit demos with it about the issues and that they should take extra care or use another port. 🤷 

In dsda-doom, while recording, tons of options are disabled by default (even if you set them on, they will be off), which avoids that confusion (although there are still many to fix, there are so many features I didn't know even exist). It's kind of a critical mass thing. Crispy is mostly safe, but with pr+ there are so many problems and the number is rising. A clearly defined set of rules on source port features is really difficult because features are added over time that didn't exist before - thus the rules need to be updated in kind and historically there is a delay, sometimes significant. One of the goals of dsda-doom is to "fix" that issue by not introducing those kinds of features in the first place - or to introduce them clearly disabled for normal speedrunning.

**Comment by JadingTsunami** [comment]
Would a standard "speedrunning config file" be a possible way to solve that?

**Comment by fabiangreffrath** [comment]
Hm, I could add an `if (demorecording)` check, though that'd be ugly.

**Comment by kraflab** [comment]
People recording FDAs or doing casual demos for testing purposes or what have you should be able to record with whatever setting they want I think. In dsda-doom these things are wrapped up in a "strict mode" which can be turned off (then the options are all open for recording). Usually the interface is kept cleaner by abstracting that check. E.g., https://github.com/kraflab/dsda-doom/blob/master/prboom2/src/dsda/settings.c#L114-L118

I'm not advocating to impose that kind of behaviour / extra work on pr+ though. dsda-doom is more strict because of its target audience and goals, and it's not a bad thing to have pr+ be more open, as it has been historically. But that's a choice for you to make I guess. A speedrunning config file could be an option, but it would need to be maintained and it would be a bit awkward because if you release a new copy then everyone would need to update it and also redo their modifications to it, so it seems a bit impractical to me.
