### ISSUE TITLE
Palette issue

### ISSUE THREAD

**Issue by hackneyed-one** [coelckers/prboom-plus#300]
So I just built from source at commit 81f20e3 and there seems to be a palette issue. It's super easy to see in the imp's fireball. This issue is not present in my older compile from May 3, 2021. I've tested both versions back and forth and back again. I'm running Ubuntu 20.04.2 LTS and I've purged prboom-plus and prboom-plus.wad from my system PATHs and between each test I clear the contents of my .prboom-plus dir (.dat .cfg) and I've rebooted to no avail. 8bit, 32bit and OpenGL affected.

![palette](https://user-images.githubusercontent.com/59325167/117144163-f5a83880-adf4-11eb-8333-34882c37c629.png)

**Comment by fabiangreffrath** [comment]
Dammit! This is because new mobjs are spawned with their bloodcolor field set to 0, which is supposed to mean "no color translation" but in fact means "transform by color translation table with index 0" which for some unknown reason is "brick". I'll have to revert the part that was meant as a simplification but turned out to mess things up.
