### ISSUE TITLE
[Feature] Fix twitched chainsaw walk bobbing

### ISSUE THREAD

**Issue by lafoxxx92** [coelckers/prboom-plus#366]

**Comment by fabiangreffrath** [comment]
This was once fixed some time ago but got reverted a short while afterwards:
https://github.com/coelckers/prboom-plus/commit/b1154ae68cf60b3e18fdd3abee2c3db4d3086d1b

The "proper" fix would be to call `A_WeaponReady()` during each tic in the Chainsaw's idle state, instead of only every fourth tic, but this would of course cause breakage elsewhere.
