### ISSUE TITLE
DSSECRET

### ISSUE THREAD

**Issue by lafoxxx92** [coelckers/prboom-plus#372]
Why not use DOOM's built-in sound file (like DSGETPOW) instead?
Current one sounds like it's from completely different game and out of place.

**Comment by fabiangreffrath** [comment]
The DSSECRET sound was taken from ZDoom and has been removed from Pr+'s assets for quite some time:
https://github.com/coelckers/prboom-plus/commit/95be60bda7de54fdc26200fbe52471195cfae12d#diff-05c107d5791a74a0ac63ebe161fbcc90f898255d12bad01d14d16b89f81ce81f

However, it is still possible for PWADs to provide their own custom DSSECRET sound. If none such suond can be found, the engine falls back to using the DSITMBK sound, which is available in all IWADs since Doom v1.2:
https://github.com/coelckers/prboom-plus/blob/f5ba5a39ad596af681ed3102fed5f28cc685089c/prboom2/src/p_spec.c#L2379
