### ISSUE TITLE
(BUG) Chaingun sound slightly out of sync

### ISSUE THREAD

**Issue by OpenRift412** [coelckers/prboom-plus#429]
There's this weird bug that's been in prboom+ since like 2.4 where the rhythm of the chaingun firing just sounds.... off, compared to other source ports. The best way I can describe it is instead of it being like "dudududududududududun", is more like "dudun dududn dudun dudun dudun". I've compared this with Chocolate, Crispy, and Woof, and PrBoom is the odd one out.

**Comment by fabiangreffrath** [comment]
Indeed, PrBoom+ has some strange sound bugs that become apparent especially when sounds are interrupted by their own dupliactes, see e.g. the discussion in https://github.com/coelckers/prboom-plus/pull/330.

**Comment by facespkz** [comment]
This even goes back to LsdlDoom, which got merged into PrBoom forever ago along with LxDoom. Lx probably has the same bug since Lsdl was mostly a windows port.

**Comment by facespkz** [comment]
Can you open up your `prboom-plus.cfg` and change `slice_samplecount` from 512 to 256?

**Comment by OpenRift412** [comment]
> Can you open up your `prboom-plus.cfg` and change `slice_samplecount` from 512 to 256?

Y'know, that actually does help a little bit, just with an occasional inconsistency in rate, as opposed to constant inconsistency. That's a good step in the right direction though!

**Comment by facespkz** [comment]
Yeah, this seems to boil down to the way that SDL_mixer works. PrBoom+ opens a sound device with SDL with a buffer length in samples, and the mixer (for whatever reason) plays sounds at the start of each buffer. This buffer also happens to be longer than a gametic, which is about 28.6 milliseconds, or 1260 samples long at 44100hz.
https://github.com/coelckers/prboom-plus/blob/1bc98e2bb70a82f3186b00a261f3e7303662b8df/prboom2/src/SDL/i_sound.c#L682
^ results in 2048 samples with a 44100 samplerate and 512 samplecount
2048/44100 = 0.046 seconds, or 46.4 milliseconds

PrBoom+ plays at 35 fps, and it runs sound code every time a gametic happens. Since the buffer length isn't equal to or smaller than a gametic, this means that these changes can sound inconsistent. Since these changes are supposed to happen at the start of each buffer, decreasing `slice_samplecount` seems like the best way to counter this.

**Comment by fabiangreffrath** [comment]
Could you suggest a formula that takes TICRATE into account?

**Comment by facespkz** [comment]
The easiest way would be something like `snd_samplerate / TICRATE`, but some audio drivers (at least mine) will round it up to a power of two, so we need a function to round it down instead. Something like what Chocolate does:
https://github.com/chocolate-doom/chocolate-doom/blob/9546b2f0392a606bb6220671741525ba40480685/src/i_sdlsound.c#L1047-L1072

Any idea on what to do with `snd_samplecount`? It's somewhat new, but fixing this problem for most people would mean changing its behavior.
