### ISSUE TITLE
Inconsistent demo playback warp system

### ISSUE THREAD

**Issue by Pedro-Beirao** [coelckers/prboom-plus#446]
The port's behaviour when -warp is used when playing back demos is very inconsistent.
Tested on version 2.6.1

Examples:

For Doom1
```
Multi level ep1 demo:
-warp 1 2  -  Starts the demo from e1m2 ✅
-warp 1 7  -  Starts the demo from e1m7 ✅
-warp 2 2  -  Does not play anything 🟠 (This might be the expected behaviour but I think it would be better if it just ignored the -warp parameter)
-warp 2 1  -  Starts the demo from e1m1 ❌

Single level e1m6 demo:
-warp 1 6  -  Does not play anything ❌
-warp 1 1  -  Starts the demo from e1m6 ❌
-warp 2 1  -  Starts the demo from e1m6 ❌
-warp 1 2  -  Does not play anything 🟠
```

For Doom2
```
Multi level ep3 demo:
-warp 21  -  Does not play anything ❌
-warp 1  -  Starts the demo from map21 ❌
-warp 22  -  Starts the demo from map22 ✅
-warp 2  -  Does not play anything ❌

Single level map27 demo:
-warp 27  -  Does not play anything ❌
-warp 1  -  Starts the demo from map27 ❌
```

**Comment by fabiangreffrath** [comment]
Could you please post the demos here so I don't have to look them up?

**Comment by Pedro-Beirao** [comment]
I just took some demos from dsdarchive

Doom1 ep1: https://dsdarchive.com/files/demos/doom/51467/ep1-524.zip
Doom1 e1m6: https://dsdarchive.com/files/demos/doom/45310/e1m6-055.zip

Doom2 ep3: https://dsdarchive.com/files/demos/doom2/52604/0833uv3.zip
Doom2 map27: https://dsdarchive.com/files/demos/doom2/33855/lv27-011.zip

**Comment by kraflab** [comment]
A small correction here, the "does not play anything" is incorrect. It does play the demo, skipping until it reaches the map you want. If it never reaches that map then it exits while skipping, which is correct I think. The reason warping to the first map fails is because the demo skipping stops when you _transition_ to the warp map, which is just an oversight I guess.

Fix from dsda-doom: https://github.com/kraflab/dsda-doom/commit/77cdbed8c400b5d240d2f7aeaa873006e760ab23

- Tracks the warp parameters separately from the startmap variable so the checks are consistent
- Checks warp parameters at the start of a demo to catch if we're warping to the map the demo starts on
- Renames demo_warp to demo_warp_reached so it's more obvious what this tracks

**Comment by kraflab** [comment]
Note that with umapinfo makes generic progression possible, so something like "if the demo started in e2, ignore warps to e3" may be wrong. In order to automatically do that we'd have to build a graph of all the map connections to find out what is possible before playing the demo. Doesn't feel worth it to me :^)

**Comment by fabiangreffrath** [comment]
Looks like the most simple solution would be to move the `e6y_G_DoWorldDone()` call from the end of `G_DoWorldDone()` to the beginning of `G_DoLoadLevel()`.

**Comment by fabiangreffrath** [comment]
> Looks like the most simple solution would be to move the `e6y_G_DoWorldDone()` call from the end of `G_DoWorldDone()` to the beginning of `G_DoLoadLevel()`.

This won't fix the `-warp 1` case. Why is this code such a complicated mess?! 😱
