### ISSUE TITLE
Crash during startup

### ISSUE THREAD

**Issue by mikeday0** [coelckers/prboom-plus#465]
This seems to occur on all commits after 7d377a1f.

```
M_LoadDefaults: Load system defaults.
 default file: /home/mike/.prboom-plus/prboom-plus.cfg
 found prboom-plus.wad

PrBoom-Plus v2.6.1um (https://github.com/coelckers/prboom-plus)
I_SetAffinityMask: manual affinity mask is 1
 found /home/mike/Games/Doom/iwad/doom2.wad
IWAD found: /home/mike/Games/Doom/iwad/doom2.wad
free(): double free detected in tcache 2
I_SignalHandler: Exiting on signal: Aborted
```
As expected, I can fix it by deleting the `fclose` call introduced by 7d377a1f:
https://github.com/coelckers/prboom-plus/blob/cefe31394bd1e569c919e17a25fcafd19804447b/prboom2/src/d_main.c#L858

**Comment by RamonUnch** [comment]
Just above we can see that the file will be already closed in case fseek succeeds (return 0) and fread fails.

https://github.com/coelckers/prboom-plus/blob/7d377a1f7969362b88762d8c70aec4ba7174726c/prboom2/src/d_main.c#L816-L819

However because fclose is in the condition of the if(), then if fclose succeeds, it returns 0 and then the I_Error() is NOT executed, and then the file get closed an other time below. (I_Error exits the game...)

Actually the fclose should just be taken out of the condition of the if() statement and should be moved in the body of if(), because it has no reasons to fail and should return 0 on success.
Fix:
```
        if (fseek (fp, header.infotableofs, SEEK_SET) ||
            fread (fileinfo, sizeof(filelump_t), length, fp) != length)
        {
          fclose(fp);
          I_Error("CheckIWAD: failed to read directory %s",iwadname);
        }
```
And the fclose at line 858 *should* be kept.
But it is not clear to me if the guy did not mean to check for !fseek() as well.

**Comment by fabiangreffrath** [comment]
Actually, the code checks if fseek() fails OR if fread() fails OR if fclose() fails and only calls I_Error() if one of them failed. Thus, fclose() has been called on the file handler in any non-failing case before it is called again in line 858. I guess the code was already correct before, just harder to read.

**Comment by kraflab** [comment]
Wow...

**Comment by kraflab** [comment]
I think I "fixed" this while hunting for the dsda-doom crash because it was flagged by cppcheck. Must have been a false positive. I'm curious why it doesn't crash for me though 🤔

**Comment by RamonUnch** [comment]
Yes but there is still a problem: let's say that fseek() fails, then I_Error() will be directly executed and fclose() will not be called (Lazy or statement). This is not a big deal though because exiting a process should close all files handles anyway.

**Comment by fabiangreffrath** [comment]
> This is not a big deal though because exiting a process should close all files handles anyway.

Right, I guess that's the sentiment behind this code. Anyway, it's much cleareras you suggested it, so I'll change the code that way.
