### ISSUE TITLE
Screen resolution not being parsed correctly

### ISSUE THREAD

**Issue by facespkz** [coelckers/prboom-plus#475]
When loading the screen resolution from a configuration file, namely anything above 320x200 and below 1280x720, the game will load at the resolution, but also save a different one when it closes. This wrong resolution is visible in the display options. Trying to save at the resolution it's supposed to will yield the same incorrect resolution.
![2022-02-14_21-50-25_01](https://user-images.githubusercontent.com/22137884/154000738-0fdd1990-ee60-4d32-a18d-bc1aab2bf314.png)
![2022-02-14_21-50-35_01](https://user-images.githubusercontent.com/22137884/154000736-68d71d66-cea8-41fd-a68c-dcc302a6880f.png)
![2022-02-14_21-50-44_01](https://user-images.githubusercontent.com/22137884/154000732-27dae4a0-2812-416a-aa1c-357d056e5bc3.png)

**Comment by facespkz** [comment]
Upon further inspection, it looks like the new code for sorting resolutions doesn't take into account the order of canonical resolutions. This is handled in `I_FillScreenResolutionsList`,

https://github.com/coelckers/prboom-plus/blob/1e2e570c60ff6dcd0130b7d32075723bedff37e2/prboom2/src/SDL/i_video.c#L791-L804

**Comment by fabiangreffrath** [comment]
Not quite exactly. The list of canonical resolutions is mostly unordered and doesn't properly sort into the list of native resolutions reported by SDL. That's the very purpose of ordering the combined list. The problem is that `current_resolution_index` points into the list before it gets ordered, which is an oversight on my side.

**Comment by facespkz** [comment]
Oh, I thought it was supposed to sort like that. My bad.

**Comment by fabiangreffrath** [comment]
Can anybody think of any reason why non-native "desired" resolutions are put to the beginning of the list? I'd rather sort them into the canonical and native resolutions than having them at index 0. What do you guys think?

**Comment by facespkz** [comment]
https://github.com/coelckers/prboom-plus/blob/1e2e570c60ff6dcd0130b7d32075723bedff37e2/prboom2/src/SDL/i_video.c#L791-L804

This snippet pushes the canonical resolutions into the list from bottom to top, then SDL comes in and puts supported resolutions in front of them. Hence the appearance.

> I'd rather sort them into the canonical and native resolutions than having them at index 0.

Should there be a toggle to switch between arrays?

**Comment by fabiangreffrath** [comment]
> This snippet pushes the canonical resolutions into the list from bottom to top, then SDL comes in and puts supported resolutions in front of them. Hence the appearance.

Yes, I know. I have written that part of the code. 😉 

> So we'd put the native resolutions into a separate array, then string them together at the end?

No. What bothers me is that we have a list of supported resolutions and if the one set in the config file isn't among them, then it's attached to the beginning of the list, i.e. right before 320x200, instead of getting properly sorted in. I'll fix that.
