### ISSUE TITLE
SIGIL E5M8 Boss Death flags active

### ISSUE THREAD

**Issue by Raddatoons** [coelckers/prboom-plus#482]
I was recently playing `SIGIL_v1_21.wad` in PrBoom+ 2.6.2 on HNTR, but when I reached the final level, the game unexpectedly cut to the end when I defeated the Spiderdemon boss. I think it was designed for any source port's non-vanilla (>4) episodes to have boss flags inactive by default for their respective final levels, but I believe those flags have been enabled on accident. Using `SIGIL_COMPAT_v1_21.wad` does not have this issue as it has specific DEHACKED flags to disable the Spiderdemon's boss death flags on E3M8.

I have not tested this on HMP or UV, where a Cyberdemon will also spawn, to see how it affects the boss flags.

I have observed this bug in multiple source ports, the main ones being Woof!, Crispy Doom, and PrBoom+. I wasn't sure if it was a shared piece of code between these source ports causing the issue or if they each have unique issues, but I am intending to make unique bug reports for each one.

**Comment by facespkz** [comment]
Woof's solution was to use UMAPINFO to disable the death action, so that's what I did. Place [this file](https://gist.github.com/facespkz/555c2a09e6d029920e5c0f4425b5f72d) into autoload/SIGIL.wad, and neither of the bosses should end the map.

I might make a pull request if this is something they'd like to have by default.

**Comment by kraflab** [comment]
See https://github.com/coelckers/prboom-plus/pull/549 for more discussion on this topic.
