### ISSUE TITLE
Quicksaving shouldn't need confirmation

### ISSUE THREAD

**Issue by mooreye** [coelckers/prboom-plus#499]
This defeats the whole purpose of quick saving, I have to stretch my hand from WASD to Y to confirm saving. I didn't manage to find an option to disable this. Actually, I find normal saving quicker, however it too requires 2x Enter press to save which is not perfect.

**Comment by fabiangreffrath** [comment]
I agree with you and have actually replaced the redundant questions in the two other source port projects that I maintain, but I don't think that PrBoom+ with its decade-long history of preserving all previous source ports' bugs and quirks is the roght project to introduce a change like this.

**Comment by mooreye** [comment]
But this doesn't affect the gameplay, does it? What harm could an opt-out menu switch do?

**Comment by kraflab** [comment]
This port is in maintenance mode and it's not a bug fix. Every feature no matter how small takes some effort to add and ultimately maintain. Since we're in maintenance mode, that means increasing the amount of maintenance required over time. Of course it seems like a tiny thing but if you do all the tiny stuff you will find you've done a lot :^)
