### ISSUE TITLE
"Disable sound cutoffs" doesnt' fully work

### ISSUE THREAD

**Issue by mooreye** [coelckers/prboom-plus#504]
If you enable this option, it plays full length of enemy wakeup sounds even if you try to interrupt it by killing/hurting the enemy which makes another sound. However, if you pick up a weapon and then quickly another item, or fall down to make a grunt sound, the weapon pickup sound will still be cut off.

**Comment by fabiangreffrath** [comment]
Yes, this is expected, because the pickup sounds are emitted "in the player's head", i.e. from `source = NULL`, and there can only be one sound emitted by one source at any given time. The wakeup sounds being uniterruptible is implemented by attaching them to the coordinate in the game world where they were emitted from (i.e. the point in space where the monster woke up), but this is impossible with the "player's own inner sound source".
