### ISSUE TITLE
[Request] PlaySound codepointer support in all complevels (possibly via compatibility menu)

### ISSUE THREAD

**Issue by SirBofu** [coelckers/prboom-plus#516]
Non-MBF complevels do not currently support some MBF codepointers. While this is likely to be expected, the absence of a compatibility setting for this feature is somewhat limiting for modders. Introducing an option similar to the sound quirks setting (or simply enabling support for the PlaySound setting.

While I'm sure there's some concern that this could cause demos to desync, I feel like this would only be the case in demos played using WADs with Dehacked patches that contain these codepointers in the first place, which I would think is an edge case. Given that complevel 2 still supports features like the Dropped Item property for Things and that Crispy Doom handles a lot of these codepointers without any apparent desync (recorded a demo in complevel 2 in PrBoom+, demo played back without issue in Crispy Doom, and vice versa), I think it would be nice to at least allow the option.

Thanks for your time.

**Comment by kraflab** [comment]
If a wad requires a higher compatibility level, then use the higher compatibility level. We're not going to change the behaviour of existing complevels, and compatibility flags only apply to mbf and higher anyway. Perhaps you could explain a bit more why modders are currently limited?

**Comment by kraflab** [comment]
`without targeting complevel 21` I mean, that's why we made mbf21 :^)
I'm not sure exactly how it was decided to "leak" some features backwards in complevels when adding new dehacked stuff in the past, but I would rather avoid any further leaking - otherwise you end up in a situation where your features only work on certain versions of prboom+ and not in others. PRBoom+ is supposed to be consistent and static for this kind of behaviour.

**Comment by SirBofu** [comment]
Closing - complevel 21 produces the desired effects, and targeting it is not breaking compatibility with other targeted source ports such as Crispy, GZDoom, etc. Will be using it going forward.
