### ISSUE TITLE
Title music in MAYhem19.wad does not work with PortMidi backend.

### ISSUE THREAD

**Issue by rfomin** [coelckers/prboom-plus#547]
@ceski-1 For some reason the GS reset message is muting the MIDI song title in [MAYhem19.wad](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/mayhem19), when using MS GS Wavetable Synth. Works with `gm_system_on` message.

**Comment by ceski-1** [comment]
For some reason the song uses instrument "variations" (e.g. bank select MSB values > 0) that aren't supported by most Roland devices or MS GS Wavetable Synth. This causes problems I won't get into (search "capital tone fallback" for more details). In GM mode, these bank selects are ignored, so the song plays fine.

Here's are two solutions:
1. Disable sysex reset by default, and make the non-sysex resets a bit more robust to compensate.
2. Emulate capital tone fallback.

Since PrBoom+ is in maintenance mode, I'll go with option 1. I'll make a PR in a bit. Maybe I'll add option 2 to some other projects.

**Comment by rfomin** [comment]
Thanks for explanation. So is the "GM System On" more compatible? Or is it useless for Roland devices?

**Comment by ceski-1** [comment]
"GM System On" is the safest setting but can make songs sound bland if they were written with GS features. GM works fine on Roland devices.
