### ISSUE TITLE
[Suggestion] Move secret area notification menu option elsewhere for improved visibility

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/prboom-plus#81]
The secret notification in PrBoom has always been placed in a very unintuitive spot compared to other ports.

I think it's finally time to make it more visible by placing the menu entry elsewhere, where it can be easily discovered. It's in such a bad place many people still don't know how to enable the notifications up to this day, let alone that PrBoom even has such a feature.

**Comment by fabiangreffrath** [comment]
Well, at least I have renamed the menu item to something more significant just today.

However, merely reporting that something is bad without providing any better alternative isn't really constructive criticism.

**Comment by sinisterseed** [comment]
> Well, at least I have renamed the menu item to something more significant just today.
> 
> However, merely reporting that something is bad without providing any better alternative isn't really constructive criticism.
Oh I know, in fact I was just in the process of discovering how to make a PR for my proposal. I am thinking about moving to General under Miscellaneous, below "Show ENDOOM Screen".

It's easy to find it there and I think it's a good place, very easy to find too.

**Comment by fabiangreffrath** [comment]
@sinisterseed To me it makes more sense to keep the option in the "advanced HUD settings" section than moving it to "Miscellaneous" among game speed, skill and compatibility options. If you agree, please close this issue, else please file a PR. Thanks!

**Comment by sinisterseed** [comment]
I still think it's better to have it there, but we may want a few more opinions on this.

Nust to avoid making a PR for nothing if I get to it.

**Comment by JadingTsunami** [comment]
Leaving it where it is in HUD settings makes sense to me. There's no user telemetry in the game and no way to test nor verify claims that it will be easier to find or get used more often in a new location. One could just as easily make the claim that moving it will cause more confusion than leaving it alone because so many people are already accustomed to where it is.

I would stick with historical inertia and leave it alone unless there is some evidence to suggest we'd actually be improving things (in some articulable, measurable way) by moving it.

**Comment by sinisterseed** [comment]
Well, I wish I read your comment before I made the PR...

Leave it there then, forget I even brought it up.
