### ISSUE TITLE
[Bug] Recent bug-fix commit breaks SDL music

### ISSUE THREAD

**Issue by physixcat** [coelckers/prboom-plus#82]
e0d4316111b0c9a04f0e22f640a55d1ff4821c49 seems to have broken SDL music, at least on Linux. Fluidsynth works, but selecting SDL will result in no music playing at all. I don't know why this is, but I thought it would be good to report it right away. Reverting to the commit right before it resulted in SDL working again.

**Comment by fabiangreffrath** [comment]
I guess the `memset()` call needs to be moved a few lines down right before the loop.

**Comment by fabiangreffrath** [comment]
@physixcat could you please check if moving the call right before the loop fixes the issue for you?

**Comment by fabiangreffrath** [comment]
I can confirm it does not fix the issue.

**Comment by fabiangreffrath** [comment]
I have just reverted that commit, we need to find another fix.

**Comment by Gustavo6046** [comment]
Perhaps the offending block of code could be skipped if not under SDL playback mode.

**Comment by fabiangreffrath** [comment]
> Perhaps the offending block of code could be skipped if not under SDL playback mode.

Yes, most probably. I guess the code inside the `if (use_experimental_music)` condition is the crucial part.

**Comment by Gustavo6046** [comment]
My suggestion did work as a temporary fix (see PR #83).

However, maybe the issue is that the music is played before other audio, so the stream buffer is already written to when we clear it if the MIDI player is the same as the audio player (in this case SDL). This is what I suspect.

In this case, we should keep this check, but move the memset to right before we call SDL's MIDI functions.
